export const skillCategories = [
    {
        name: 'Languages',
        skills: [
            'Java',
            'Python',
            'Swift',
            'Objective-C',
            'C#',
            'Golang',
            'TypeScript',
            'JavaScript',
            'C++',
            'PHP',
            'Kotlin',
            'Go',
            'Dart'
        ],
    },
    {
        name: 'Technologies',
        skills: [
            'Spring',
            'PostgreSQL',
            'Docker',
            'Kubernetes',
            'AWS',
            'Azure',
            'CI/CD',
            'Git',
            'Linux',
            'Next.js',
            'React.js',
            'Tailwind CSS',
            'SwiftUI',
            'UIKit',
            'FastAPI',
            'Flask',
            'Express.js',
            'Laravel',
        ],
    },
    {
        name: 'Cloud',
        skills: [
            'AWS',
            'GCP',
            'Azure',
            'Terraform',
            'CloudFormation',
            'Google Cloud Storage',
            'AWS Lambda',
            'Azure Functions',
            'Google Kubernetes Engine (GKE)',
        ],
    },
    {
        name: 'Databases',
        skills: [
            'PostgreSQL',
            'MongoDB',
            'Redis',
            'Elasticsearch',
            'MySQL',
            'ClickHouse',
            'SQLite',
            'MariaDB',
            'Firebase',
        ],
    },
    {
        name: 'Tools',
        skills: [
            'Jenkins',
            'GitLab CI',
            'GitHub Actions',
            'Ansible',
            'Prometheus',
            'Grafana',
            'Jira',
            'VS Code',
            'IntelliJ IDEA',
            'Docker Compose',
        ],
    },
    {
        name: 'Frameworks',
        skills: [
            'Angular',
            'Vue.js',
            'ASP.NET',
            'Spring Boot',
            'Flutter',
            'React Native',
            'Electron',
        ],
    },
    {
        name: 'Frontend',
        skills: [
            'HTML5',
            'CSS3',
            'SASS/SCSS',
            'Bootstrap',
            'Material UI',
            'Tailwind CSS',
            'Shadcn',
            'Webpack',
            'Babel',
            'TypeScript',
            'Responsive Design',
            'Next.js',
            'React',
            'Vue',
            'Svelte'
        ],
    },
    {
        name: 'Backend',
        skills: [
            'Spring',
            'FastAPI',
            'ASP.NET Core',
            'GraphQL',
            'SocksJS',
        ],
    },
    {
        name: 'Mobile Development',
        skills: [
            'SwiftUI',
            'UIKit',
        ],
    },
    {
        name: 'Security',
        skills: [
            'OWASP',
            'JWT',
            'OAuth',
            'SSL/TLS',
            'Firewalls',
            'Penetration Testing',
            'SIEM',
            'IDS/IPS',
            'Encryption',
            'Vulnerability Assessment',
        ],
    },
    {
        name: 'Version Control',
        skills: [
            'Git',
            'Bitbucket',
            'GitHub',
            'GitLab',
        ],
    },
    {
        name: 'Server Administration',
        skills: [
            'Linux Administration',
            'Windows Server',
            'Shell Scripting',
            'PowerShell',
            'Nginx',
            'Apache',
            'HAProxy',
            'Load Balancing',
            'Monitoring',
        ],
    },
    {
        name: 'VPN Development',
        skills: [
            'OpenVPN',
            'WireGuard',
            'Xray Core',
            'Singbox',
            '3x-ui',
            'Marzban'
        ],
    },
    {
        name: 'Server-Side Scripting',
        skills: [
            'Node.js',
            'Python Scripts',
            'Bash Scripting',
            'PowerShell',
        ],
    },
    {
        name: 'Status Monitoring',
        skills: [
            'Prometheus',
            'Grafana',
            'ELK Stack',
        ],
    },
    {
        name: 'Desktop Applications',
        skills: [
            'Electron',
            'WPF',
            'Flutter',
            'Qt',
        ],
    },
];
